package lua

////////////////////////////////////////////////////////
// This file was generated by go-inline. DO NOT EDIT. //
////////////////////////////////////////////////////////

import (
	"fmt"
	"sort"
	"strings"
)

func mainLoop(L *LState, baseframe *callFrame) {
	var inst uint32
	var cf *callFrame

	if L.stack.IsEmpty() {
		return
	}

	L.currentFrame = L.stack.Last()
	if L.currentFrame.Fn.IsG {
		callGFunction(L, false)
		return
	}

	for {
		cf = L.currentFrame
		inst = cf.Fn.Proto.Code[cf.Pc]
		cf.Pc++
		if L.gasLimit > 0 {
			L.gasUsed++
			if L.gasUsed > L.gasLimit {
				L.RaiseError("lua: gas limit exceeded")
				return
			}
		}
		if L.lineHook != nil {
			line := 0
			source := ""
			if cf.Fn != nil && cf.Fn.Proto != nil {
				source = cf.Fn.Proto.SourceName
			}
			if cf.Fn != nil && cf.Fn.Proto != nil && cf.Pc-1 >= 0 && cf.Pc-1 < len(cf.Fn.Proto.DbgSourcePositions) {
				line = cf.Fn.Proto.DbgSourcePositions[cf.Pc-1]
			}
			L.lineHook(source, line)
		}
		if jumpTable[int(inst>>26)](L, inst, baseframe) == 1 {
			return
		}
	}
}

// regv is the first target register to copy the return values to.
// It can be reg.top, indicating that the copied values are going into new registers, or it can be below reg.top
// Indicating that the values should be within the existing registers.
// b is the available number of return values + 1.
// n is the desired number of return values.
// If n more than the available return values then the extra values are set to nil.
// When this function returns the top of the registry will be set to regv+n.
func copyReturnValues(L *LState, regv, start, n, b int) { // +inline-start
	if b == 1 {
		// this section is inlined by go-inline
		// source function is 'func (rg *registry) FillNil(regm, n int) ' in '_state.go'
		{
			rg := L.reg
			regm := regv
			newSize := regm + n
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
			{
				requiredSize := newSize
				if requiredSize > cap(rg.array) {
					rg.resize(requiredSize)
				}
			}
			for i := 0; i < n; i++ {
				rg.array[regm+i] = LNil
			}
			// values beyond top don't need to be valid LValues, so setting them to nil is fine
			// setting them to nil rather than LNil lets us invoke the golang memclr opto
			oldtop := rg.top
			rg.top = regm + n
			if rg.top < oldtop {
				nilRange := rg.array[rg.top:oldtop]
				for i := range nilRange {
					nilRange[i] = nil
				}
			}
		}
	} else {
		// this section is inlined by go-inline
		// source function is 'func (rg *registry) CopyRange(regv, start, limit, n int) ' in '_state.go'
		{
			rg := L.reg
			limit := -1
			newSize := regv + n
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
			{
				requiredSize := newSize
				if requiredSize > cap(rg.array) {
					rg.resize(requiredSize)
				}
			}
			if limit == -1 || limit > rg.top {
				limit = rg.top
			}
			for i := 0; i < n; i++ {
				srcIdx := start + i
				if srcIdx >= limit || srcIdx < 0 {
					rg.array[regv+i] = LNil
				} else {
					rg.array[regv+i] = rg.array[srcIdx]
				}
			}

			// values beyond top don't need to be valid LValues, so setting them to nil is fine
			// setting them to nil rather than LNil lets us invoke the golang memclr opto
			oldtop := rg.top
			rg.top = regv + n
			if rg.top < oldtop {
				nilRange := rg.array[rg.top:oldtop]
				for i := range nilRange {
					nilRange[i] = nil
				}
			}
		}
		if b > 1 && n > (b-1) {
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) FillNil(regm, n int) ' in '_state.go'
			{
				rg := L.reg
				regm := regv + b - 1
				n := n - (b - 1)
				newSize := regm + n
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				for i := 0; i < n; i++ {
					rg.array[regm+i] = LNil
				}
				// values beyond top don't need to be valid LValues, so setting them to nil is fine
				// setting them to nil rather than LNil lets us invoke the golang memclr opto
				oldtop := rg.top
				rg.top = regm + n
				if rg.top < oldtop {
					nilRange := rg.array[rg.top:oldtop]
					for i := range nilRange {
						nilRange[i] = nil
					}
				}
			}
		}
	}
} // +inline-end

func callGFunction(L *LState, tailcall bool) bool {
	frame := L.currentFrame
	gfnret := frame.Fn.GFunction(L)
	if tailcall {
		L.currentFrame = L.RemoveCallerFrame()
	}

	if gfnret < 0 {
		L.RaiseError("coroutine support is disabled")
	}

	wantret := frame.NRet
	if wantret == MultRet {
		wantret = gfnret
	}

	// this section is inlined by go-inline
	// source function is 'func (rg *registry) CopyRange(regv, start, limit, n int) ' in '_state.go'
	{
		rg := L.reg
		regv := frame.ReturnBase
		start := L.reg.Top() - gfnret
		limit := -1
		n := wantret
		newSize := regv + n
		// this section is inlined by go-inline
		// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
		{
			requiredSize := newSize
			if requiredSize > cap(rg.array) {
				rg.resize(requiredSize)
			}
		}
		if limit == -1 || limit > rg.top {
			limit = rg.top
		}
		for i := 0; i < n; i++ {
			srcIdx := start + i
			if srcIdx >= limit || srcIdx < 0 {
				rg.array[regv+i] = LNil
			} else {
				rg.array[regv+i] = rg.array[srcIdx]
			}
		}

		// values beyond top don't need to be valid LValues, so setting them to nil is fine
		// setting them to nil rather than LNil lets us invoke the golang memclr opto
		oldtop := rg.top
		rg.top = regv + n
		if rg.top < oldtop {
			nilRange := rg.array[rg.top:oldtop]
			for i := range nilRange {
				nilRange[i] = nil
			}
		}
	}
	L.stack.Pop()
	L.currentFrame = L.stack.Last()
	return false
}

func threadRun(L *LState) {
	if L.stack.IsEmpty() {
		return
	}

	defer func() {
		if rcv := recover(); rcv != nil {
			panic(rcv)
		}
	}()
	L.mainLoop(L, nil)
}

type instFunc func(*LState, uint32, *callFrame) int

var jumpTable [opCodeMax + 1]instFunc

func init() {
	jumpTable = [opCodeMax + 1]instFunc{
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_MOVE
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			v := reg.Get(lbase + B)
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_MOVEN
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			v := reg.Get(lbase + B)
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := lbase + A
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			code := cf.Fn.Proto.Code
			pc := cf.Pc
			for i := 0; i < C; i++ {
				inst = code[pc]
				pc++
				A = int(inst>>18) & 0xff //GETA
				B = int(inst & 0x1ff)    //GETB
				v := reg.Get(lbase + B)
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := lbase + A
					vali := v
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			}
			cf.Pc = pc
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_LOADK
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			Bx := int(inst & 0x3ffff) //GETBX
			v := cf.Fn.Proto.Constants[Bx]
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_LOADBOOL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			if B != 0 {
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := RA
					vali := LTrue
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			} else {
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := RA
					vali := LFalse
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			}
			if C != 0 {
				cf.Pc++
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_LOADNIL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			if n := lbase + B - RA + 1; n > 1 {
				L.chargeGas(uint64(n))
			}
			for i := RA; i <= lbase+B; i++ {
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := i
					vali := LNil
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_GETUPVAL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			v := cf.Fn.Upvalues[B].Value()
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_GETGLOBAL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			Bx := int(inst & 0x3ffff) //GETBX
			//reg.Set(RA, L.getField(cf.Fn.Env, cf.Fn.Proto.Constants[Bx]))
			v := L.getFieldString(cf.Fn.Env, cf.Fn.Proto.stringConstants[Bx])
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_GETTABLE
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			v := L.getField(reg.Get(lbase+B), L.rkValue(C))
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_GETTABLEKS
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			v := L.getFieldString(reg.Get(lbase+B), L.rkString(C))
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_SETGLOBAL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			Bx := int(inst & 0x3ffff) //GETBX
			//L.setField(cf.Fn.Env, cf.Fn.Proto.Constants[Bx], reg.Get(RA))
			L.setFieldString(cf.Fn.Env, cf.Fn.Proto.stringConstants[Bx], reg.Get(RA))
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_SETUPVAL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			cf.Fn.Upvalues[B].SetValue(reg.Get(RA))
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_SETTABLE
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			L.setField(reg.Get(RA), L.rkValue(B), L.rkValue(C))
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_SETTABLEKS
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			L.setFieldString(reg.Get(RA), L.rkString(B), L.rkValue(C))
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_NEWTABLE
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			v := newLTable(B, C)
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_SELF
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			selfobj := reg.Get(lbase + B)
			v := L.getFieldString(selfobj, L.rkString(C))
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA + 1
				vali := selfobj
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		opArith, // OP_ADD
		opArith, // OP_SUB
		opArith, // OP_MUL
		opArith, // OP_DIV
		opArith, // OP_MOD
		opArith, // OP_POW
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_UNM
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			unaryv := L.rkValue(B)
			if lv, ok := unaryv.(LUint256); ok {
				// Two's complement negation: -n = 0 - n (wraps mod 2^256).
				// Consistent with EVM semantics: -1 == 2^256-1.
				result := lu256Sub(LUint256Zero, lv)
				{
					rg := reg
					regi := RA
					newSize := regi + 1
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = result
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			} else {
				op := L.metaOp1(unaryv, "__unm")
				if op.Type() == LTFunction {
					reg.Push(op)
					reg.Push(unaryv)
					reg.Push(unaryv)
					L.Call(2, 1)
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
					{
						rg := reg
						regi := RA
						vali := reg.Pop()
						newSize := regi + 1
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
						{
							requiredSize := newSize
							if requiredSize > cap(rg.array) {
								rg.resize(requiredSize)
							}
						}
						rg.array[regi] = vali
						if regi >= rg.top {
							rg.top = regi + 1
						}
					}
				} else if str, ok1 := unaryv.(LString); ok1 {
					if _, err := parseNumber(string(str)); err == nil {
						L.RaiseError("__unm undefined for uint256 numbers")
					} else {
						L.RaiseError("__unm undefined")
					}
				} else {
					L.RaiseError("__unm undefined")
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_NOT
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			if LVIsFalse(reg.Get(lbase + B)) {
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := RA
					vali := LTrue
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			} else {
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := RA
					vali := LFalse
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_LEN
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			switch lv := L.rkValue(B).(type) {
			case LString:
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) SetNumber(regi int, vali LUint256) ' in '_state.go'
				{
					rg := reg
					regi := RA
					vali := lu256FromInt(len(lv))
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = rg.alloc.LUint256ToI(vali)
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			default:
				op := L.metaOp1(lv, "__len")
				if op.Type() == LTFunction {
					reg.Push(op)
					reg.Push(lv)
					reg.Push(lv)
					L.Call(2, 1)
					ret := reg.Pop()
					if ret.Type() == LTUint256 {
						v, _ := ret.(LUint256)
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) SetNumber(regi int, vali LUint256) ' in '_state.go'
						{
							rg := reg
							regi := RA
							vali := v
							newSize := regi + 1
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							rg.array[regi] = rg.alloc.LUint256ToI(vali)
							if regi >= rg.top {
								rg.top = regi + 1
							}
						}
					} else {
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
						{
							rg := reg
							regi := RA
							vali := ret
							newSize := regi + 1
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							rg.array[regi] = vali
							if regi >= rg.top {
								rg.top = regi + 1
							}
						}
					}
				} else if lv.Type() == LTTable {
					n, cost := lv.(*LTable).LenWithCost()
					chargeLinearWorkGas(L, cost)
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) SetNumber(regi int, vali LUint256) ' in '_state.go'
					{
						rg := reg
						regi := RA
						vali := lu256FromInt(n)
						newSize := regi + 1
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
						{
							requiredSize := newSize
							if requiredSize > cap(rg.array) {
								rg.resize(requiredSize)
							}
						}
						rg.array[regi] = rg.alloc.LUint256ToI(vali)
						if regi >= rg.top {
							rg.top = regi + 1
						}
					}
				} else {
					L.RaiseError("__len undefined")
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_CONCAT
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			RC := lbase + C
			RB := lbase + B
			v := stringConcat(L, RC-RB+1, RC)
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := v
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_JMP
			cf := L.currentFrame
			Sbx := int(inst&0x3ffff) - opMaxArgSbx //GETSBX
			cf.Pc += Sbx
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_EQ
			cf := L.currentFrame
			A := int(inst>>18) & 0xff //GETA
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			ret := equals(L, L.rkValue(B), L.rkValue(C), false)
			v := 1
			if ret {
				v = 0
			}
			if v == A {
				cf.Pc++
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_LT
			cf := L.currentFrame
			A := int(inst>>18) & 0xff //GETA
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			ret := lessThan(L, L.rkValue(B), L.rkValue(C))
			v := 1
			if ret {
				v = 0
			}
			if v == A {
				cf.Pc++
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_LE
			cf := L.currentFrame
			A := int(inst>>18) & 0xff //GETA
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			lhs := L.rkValue(B)
			rhs := L.rkValue(C)
			ret := false

			if v1, ok1 := lhs.(LUint256); ok1 {
				if v2, ok2 := rhs.(LUint256); ok2 {
					ret = lu256Cmp(v1, v2) <= 0
				} else {
					// Mixed types: try __le on either operand.
					m := L.metaOp1(lhs, "__le")
					if m.Type() != LTFunction {
						m = L.metaOp1(rhs, "__le")
					}
					if m.Type() == LTFunction {
						L.reg.Push(m)
						L.reg.Push(lhs)
						L.reg.Push(rhs)
						L.Call(2, 1)
						ret = LVAsBool(L.reg.Pop())
					} else {
						L.RaiseError("attempt to compare %v with %v", lhs.Type().String(), rhs.Type().String())
					}
				}
			} else {
				if lhs.Type() != rhs.Type() {
					// Try __le on either operand for mixed-type comparisons.
					m := L.metaOp1(lhs, "__le")
					if m.Type() != LTFunction {
						m = L.metaOp1(rhs, "__le")
					}
					if m.Type() == LTFunction {
						L.reg.Push(m)
						L.reg.Push(lhs)
						L.reg.Push(rhs)
						L.Call(2, 1)
						ret = LVAsBool(L.reg.Pop())
					} else {
						L.RaiseError("attempt to compare %v with %v", lhs.Type().String(), rhs.Type().String())
					}
				} else {
					switch lhs.Type() {
					case LTString:
						ret = strCmp(string(lhs.(LString)), string(rhs.(LString))) <= 0
					default:
						switch objectRational(L, lhs, rhs, "__le") {
						case 1:
							ret = true
						case 0:
							ret = false
						default:
							ret = !objectRationalWithError(L, rhs, lhs, "__lt")
						}
					}
				}
			}

			v := 1
			if ret {
				v = 0
			}
			if v == A {
				cf.Pc++
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_TEST
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			C := int(inst>>9) & 0x1ff //GETC
			if LVAsBool(reg.Get(RA)) == (C == 0) {
				cf.Pc++
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_TESTSET
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			if value := reg.Get(lbase + B); LVAsBool(value) != (C == 0) {
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := RA
					vali := value
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			} else {
				cf.Pc++
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_CALL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			nargs := B - 1
			if B == 0 {
				nargs = reg.Top() - (RA + 1)
			}
			lv := reg.Get(RA)
			nret := C - 1
			var callable *LFunction
			var meta bool
			if fn, ok := lv.(*LFunction); ok {
				callable = fn
				meta = false
			} else {
				callable, meta = L.metaCall(lv)
			}
			// this section is inlined by go-inline
			// source function is 'func (ls *LState) pushCallFrame(cf callFrame, fn LValue, meta bool) ' in '_state.go'
			{
				ls := L
				cf := callFrame{Fn: callable, Pc: 0, Base: RA, LocalBase: RA + 1, ReturnBase: RA, NArgs: nargs, NRet: nret, Parent: cf, TailCall: 0}
				fn := lv
				if meta {
					cf.NArgs++
					ls.reg.Insert(fn, cf.LocalBase)
				}
				if cf.Fn == nil {
					ls.RaiseError("attempt to call a non-function object")
				}
				if ls.stack.IsFull() {
					ls.RaiseError("stack overflow")
				}
				ls.stack.Push(cf)
				newcf := ls.stack.Last()
				// this section is inlined by go-inline
				// source function is 'func (ls *LState) initCallFrame(cf *callFrame) ' in '_state.go'
				{
					cf := newcf
					if cf.Fn.IsG {
						ls.reg.SetTop(cf.LocalBase + cf.NArgs)
					} else {
						proto := cf.Fn.Proto
						nargs := cf.NArgs
						np := int(proto.NumParameters)
						if nargs < np {
							// default any missing arguments to nil
							newSize := cf.LocalBase + np
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								rg := ls.reg
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							for i := nargs; i < np; i++ {
								ls.reg.array[cf.LocalBase+i] = LNil
							}
							nargs = np
							ls.reg.top = newSize
						}

						if (proto.IsVarArg & VarArgIsVarArg) == 0 {
							if nargs < int(proto.NumUsedRegisters) {
								nargs = int(proto.NumUsedRegisters)
							}
							newSize := cf.LocalBase + nargs
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								rg := ls.reg
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							for i := np; i < nargs; i++ {
								ls.reg.array[cf.LocalBase+i] = LNil
							}
							ls.reg.top = cf.LocalBase + int(proto.NumUsedRegisters)
						} else {
							/* swap vararg positions:
									   closure
									   namedparam1 <- lbase
									   namedparam2
									   vararg1
									   vararg2

							           TO

									   closure
									   nil
									   nil
									   vararg1
									   vararg2
									   namedparam1 <- lbase
									   namedparam2
							*/
							nvarargs := nargs - np
							if nvarargs < 0 {
								nvarargs = 0
							}

							ls.reg.SetTop(cf.LocalBase + nargs + np)
							for i := 0; i < np; i++ {
								//ls.reg.Set(cf.LocalBase+nargs+i, ls.reg.Get(cf.LocalBase+i))
								ls.reg.array[cf.LocalBase+nargs+i] = ls.reg.array[cf.LocalBase+i]
								//ls.reg.Set(cf.LocalBase+i, LNil)
								ls.reg.array[cf.LocalBase+i] = LNil
							}

							if CompatVarArg {
								ls.reg.SetTop(cf.LocalBase + nargs + np + 1)
								if (proto.IsVarArg & VarArgNeedsArg) != 0 {
									argtb := newLTable(nvarargs, 0)
									for i := 0; i < nvarargs; i++ {
										argtb.RawSetInt(i+1, ls.reg.Get(cf.LocalBase+np+i))
									}
									argtb.RawSetString("n", lu256FromInt(nvarargs))
									//ls.reg.Set(cf.LocalBase+nargs+np, argtb)
									ls.reg.array[cf.LocalBase+nargs+np] = argtb
								} else {
									ls.reg.array[cf.LocalBase+nargs+np] = LNil
								}
							}
							cf.LocalBase += nargs
							maxreg := cf.LocalBase + int(proto.NumUsedRegisters)
							ls.reg.SetTop(maxreg)
						}
					}
				}
				ls.currentFrame = newcf
			}
			if callable.IsG && callGFunction(L, false) {
				return 1
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_TAILCALL
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			nargs := B - 1
			if B == 0 {
				nargs = reg.Top() - (RA + 1)
			}
			lv := reg.Get(RA)
			var callable *LFunction
			var meta bool
			if fn, ok := lv.(*LFunction); ok {
				callable = fn
				meta = false
			} else {
				callable, meta = L.metaCall(lv)
			}
			if callable == nil {
				L.RaiseError("attempt to call a non-function object")
			}
			// this section is inlined by go-inline
			// source function is 'func (ls *LState) closeUpvalues(idx int) ' in '_state.go'
			{
				ls := L
				idx := lbase
				if ls.uvcache != nil {
					var prev *Upvalue
					for uv := ls.uvcache; uv != nil; uv = uv.next {
						if uv.index >= idx {
							if prev != nil {
								prev.next = nil
							} else {
								ls.uvcache = nil
							}
							uv.Close()
						}
						prev = uv
					}
				}
			}
			if callable.IsG {
				luaframe := cf
				L.pushCallFrame(callFrame{
					Fn:         callable,
					Pc:         0,
					Base:       RA,
					LocalBase:  RA + 1,
					ReturnBase: cf.ReturnBase,
					NArgs:      nargs,
					NRet:       cf.NRet,
					Parent:     cf,
					TailCall:   0,
				}, lv, meta)
				if callGFunction(L, true) {
					return 1
				}
				if L.currentFrame == nil || L.currentFrame.Fn.IsG || luaframe == baseframe {
					return 1
				}
			} else {
				base := cf.Base
				cf.Fn = callable
				cf.Pc = 0
				cf.Base = RA
				cf.LocalBase = RA + 1
				cf.ReturnBase = cf.ReturnBase
				cf.NArgs = nargs
				cf.NRet = cf.NRet
				cf.TailCall++
				lbase := cf.LocalBase
				if meta {
					cf.NArgs++
					L.reg.Insert(lv, cf.LocalBase)
				}
				// this section is inlined by go-inline
				// source function is 'func (ls *LState) initCallFrame(cf *callFrame) ' in '_state.go'
				{
					ls := L
					if cf.Fn.IsG {
						ls.reg.SetTop(cf.LocalBase + cf.NArgs)
					} else {
						proto := cf.Fn.Proto
						nargs := cf.NArgs
						np := int(proto.NumParameters)
						if nargs < np {
							// default any missing arguments to nil
							newSize := cf.LocalBase + np
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								rg := ls.reg
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							for i := nargs; i < np; i++ {
								ls.reg.array[cf.LocalBase+i] = LNil
							}
							nargs = np
							ls.reg.top = newSize
						}

						if (proto.IsVarArg & VarArgIsVarArg) == 0 {
							if nargs < int(proto.NumUsedRegisters) {
								nargs = int(proto.NumUsedRegisters)
							}
							newSize := cf.LocalBase + nargs
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								rg := ls.reg
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							for i := np; i < nargs; i++ {
								ls.reg.array[cf.LocalBase+i] = LNil
							}
							ls.reg.top = cf.LocalBase + int(proto.NumUsedRegisters)
						} else {
							/* swap vararg positions:
									   closure
									   namedparam1 <- lbase
									   namedparam2
									   vararg1
									   vararg2

							           TO

									   closure
									   nil
									   nil
									   vararg1
									   vararg2
									   namedparam1 <- lbase
									   namedparam2
							*/
							nvarargs := nargs - np
							if nvarargs < 0 {
								nvarargs = 0
							}

							ls.reg.SetTop(cf.LocalBase + nargs + np)
							for i := 0; i < np; i++ {
								//ls.reg.Set(cf.LocalBase+nargs+i, ls.reg.Get(cf.LocalBase+i))
								ls.reg.array[cf.LocalBase+nargs+i] = ls.reg.array[cf.LocalBase+i]
								//ls.reg.Set(cf.LocalBase+i, LNil)
								ls.reg.array[cf.LocalBase+i] = LNil
							}

							if CompatVarArg {
								ls.reg.SetTop(cf.LocalBase + nargs + np + 1)
								if (proto.IsVarArg & VarArgNeedsArg) != 0 {
									argtb := newLTable(nvarargs, 0)
									for i := 0; i < nvarargs; i++ {
										argtb.RawSetInt(i+1, ls.reg.Get(cf.LocalBase+np+i))
									}
									argtb.RawSetString("n", lu256FromInt(nvarargs))
									//ls.reg.Set(cf.LocalBase+nargs+np, argtb)
									ls.reg.array[cf.LocalBase+nargs+np] = argtb
								} else {
									ls.reg.array[cf.LocalBase+nargs+np] = LNil
								}
							}
							cf.LocalBase += nargs
							maxreg := cf.LocalBase + int(proto.NumUsedRegisters)
							ls.reg.SetTop(maxreg)
						}
					}
				}
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) CopyRange(regv, start, limit, n int) ' in '_state.go'
				{
					rg := L.reg
					regv := base
					start := RA
					limit := -1
					n := reg.Top() - RA - 1
					newSize := regv + n
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					if limit == -1 || limit > rg.top {
						limit = rg.top
					}
					for i := 0; i < n; i++ {
						srcIdx := start + i
						if srcIdx >= limit || srcIdx < 0 {
							rg.array[regv+i] = LNil
						} else {
							rg.array[regv+i] = rg.array[srcIdx]
						}
					}

					// values beyond top don't need to be valid LValues, so setting them to nil is fine
					// setting them to nil rather than LNil lets us invoke the golang memclr opto
					oldtop := rg.top
					rg.top = regv + n
					if rg.top < oldtop {
						nilRange := rg.array[rg.top:oldtop]
						for i := range nilRange {
							nilRange[i] = nil
						}
					}
				}
				cf.Base = base
				cf.LocalBase = base + (cf.LocalBase - lbase + 1)
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_RETURN
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			// this section is inlined by go-inline
			// source function is 'func (ls *LState) closeUpvalues(idx int) ' in '_state.go'
			{
				ls := L
				idx := lbase
				if ls.uvcache != nil {
					var prev *Upvalue
					for uv := ls.uvcache; uv != nil; uv = uv.next {
						if uv.index >= idx {
							if prev != nil {
								prev.next = nil
							} else {
								ls.uvcache = nil
							}
							uv.Close()
						}
						prev = uv
					}
				}
			}
			nret := B - 1
			if B == 0 {
				nret = reg.Top() - RA
			}
			n := cf.NRet
			if cf.NRet == MultRet {
				n = nret
			}

			islast := baseframe == L.stack.Pop() || L.stack.IsEmpty()
			// this section is inlined by go-inline
			// source function is 'func copyReturnValues(L *LState, regv, start, n, b int) ' in '_vm.go'
			{
				regv := cf.ReturnBase
				start := RA
				b := B
				if b == 1 {
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) FillNil(regm, n int) ' in '_state.go'
					{
						rg := L.reg
						regm := regv
						newSize := regm + n
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
						{
							requiredSize := newSize
							if requiredSize > cap(rg.array) {
								rg.resize(requiredSize)
							}
						}
						for i := 0; i < n; i++ {
							rg.array[regm+i] = LNil
						}
						// values beyond top don't need to be valid LValues, so setting them to nil is fine
						// setting them to nil rather than LNil lets us invoke the golang memclr opto
						oldtop := rg.top
						rg.top = regm + n
						if rg.top < oldtop {
							nilRange := rg.array[rg.top:oldtop]
							for i := range nilRange {
								nilRange[i] = nil
							}
						}
					}
				} else {
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) CopyRange(regv, start, limit, n int) ' in '_state.go'
					{
						rg := L.reg
						limit := -1
						newSize := regv + n
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
						{
							requiredSize := newSize
							if requiredSize > cap(rg.array) {
								rg.resize(requiredSize)
							}
						}
						if limit == -1 || limit > rg.top {
							limit = rg.top
						}
						for i := 0; i < n; i++ {
							srcIdx := start + i
							if srcIdx >= limit || srcIdx < 0 {
								rg.array[regv+i] = LNil
							} else {
								rg.array[regv+i] = rg.array[srcIdx]
							}
						}

						// values beyond top don't need to be valid LValues, so setting them to nil is fine
						// setting them to nil rather than LNil lets us invoke the golang memclr opto
						oldtop := rg.top
						rg.top = regv + n
						if rg.top < oldtop {
							nilRange := rg.array[rg.top:oldtop]
							for i := range nilRange {
								nilRange[i] = nil
							}
						}
					}
					if b > 1 && n > (b-1) {
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) FillNil(regm, n int) ' in '_state.go'
						{
							rg := L.reg
							regm := regv + b - 1
							n := n - (b - 1)
							newSize := regm + n
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							for i := 0; i < n; i++ {
								rg.array[regm+i] = LNil
							}
							// values beyond top don't need to be valid LValues, so setting them to nil is fine
							// setting them to nil rather than LNil lets us invoke the golang memclr opto
							oldtop := rg.top
							rg.top = regm + n
							if rg.top < oldtop {
								nilRange := rg.array[rg.top:oldtop]
								for i := range nilRange {
									nilRange[i] = nil
								}
							}
						}
					}
				}
			}
			L.currentFrame = L.stack.Last()
			if islast || L.currentFrame == nil || L.currentFrame.Fn.IsG {
				return 1
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_FORLOOP
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			if init, ok1 := reg.Get(RA).(LUint256); ok1 {
				if limit, ok2 := reg.Get(RA + 1).(LUint256); ok2 {
					if step, ok3 := reg.Get(RA + 2).(LUint256); ok3 {
						v := lu256Add(init, step)
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) SetNumber(regi int, vali LUint256) ' in '_state.go'
						{
							rg := reg
							regi := RA
							vali := v
							newSize := regi + 1
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
							{
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							rg.array[regi] = rg.alloc.LUint256ToI(vali)
							if regi >= rg.top {
								rg.top = regi + 1
							}
						}
						// Use two's complement sign semantics (bit 255) to determine
						// loop direction — consistent with EVM SDIV/SLT/SGT/SAR:
						//   step "negative" (bit 255 set)  → count down: continue while v >= limit (signed)
						//   step "positive" (bit 255 clear) → count up:   continue while v <= limit (unsigned)
						// Signed comparison is required for the negative-step case so that when v
						// wraps past zero (e.g. goes from 1 to 2^256-1) the loop terminates.
						if (!lu256IsNeg(step) && lu256Cmp(v, limit) <= 0) ||
							(lu256IsNeg(step) && lu256SCmp(v, limit) >= 0) {
							Sbx := int(inst&0x3ffff) - opMaxArgSbx //GETSBX
							cf.Pc += Sbx
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) SetNumber(regi int, vali LUint256) ' in '_state.go'
							{
								rg := reg
								regi := RA + 3
								vali := v
								newSize := regi + 1
								// this section is inlined by go-inline
								// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
								{
									requiredSize := newSize
									if requiredSize > cap(rg.array) {
										rg.resize(requiredSize)
									}
								}
								rg.array[regi] = rg.alloc.LUint256ToI(vali)
								if regi >= rg.top {
									rg.top = regi + 1
								}
							}
						} else {
							// this section is inlined by go-inline
							// source function is 'func (rg *registry) SetTop(topi int) ' in '_state.go'
							{
								rg := reg
								topi := RA + 1
								// this section is inlined by go-inline
								// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
								{
									requiredSize := topi
									if requiredSize > cap(rg.array) {
										rg.resize(requiredSize)
									}
								}
								oldtopi := rg.top
								rg.top = topi
								for i := oldtopi; i < rg.top; i++ {
									rg.array[i] = LNil
								}
								// values beyond top don't need to be valid LValues, so setting them to nil is fine
								// setting them to nil rather than LNil lets us invoke the golang memclr opto
								if rg.top < oldtopi {
									nilRange := rg.array[rg.top:oldtopi]
									for i := range nilRange {
										nilRange[i] = nil
									}
								}
								//for i := rg.top; i < oldtop; i++ {
								//	rg.array[i] = LNil
								//}
							}
						}
					} else {
						L.RaiseError("for statement step must be a number")
					}
				} else {
					L.RaiseError("for statement limit must be a number")
				}
			} else {
				L.RaiseError("for statement init must be a number")
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_FORPREP
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			Sbx := int(inst&0x3ffff) - opMaxArgSbx //GETSBX
			if init, ok1 := reg.Get(RA).(LUint256); ok1 {
				if step, ok2 := reg.Get(RA + 2).(LUint256); ok2 {
					prep := lu256Sub(init, step)
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) SetNumber(regi int, vali LUint256) ' in '_state.go'
					{
						rg := reg
						regi := RA
						vali := prep
						newSize := regi + 1
						// this section is inlined by go-inline
						// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
						{
							requiredSize := newSize
							if requiredSize > cap(rg.array) {
								rg.resize(requiredSize)
							}
						}
						rg.array[regi] = rg.alloc.LUint256ToI(vali)
						if regi >= rg.top {
							rg.top = regi + 1
						}
					}
				} else {
					L.RaiseError("for statement step must be a number")
				}
			} else {
				L.RaiseError("for statement init must be a number")
			}
			cf.Pc += Sbx
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_TFORLOOP
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			C := int(inst>>9) & 0x1ff //GETC
			nret := C
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) SetTop(topi int) ' in '_state.go'
			{
				rg := reg
				topi := RA + 3 + 2
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := topi
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				oldtopi := rg.top
				rg.top = topi
				for i := oldtopi; i < rg.top; i++ {
					rg.array[i] = LNil
				}
				// values beyond top don't need to be valid LValues, so setting them to nil is fine
				// setting them to nil rather than LNil lets us invoke the golang memclr opto
				if rg.top < oldtopi {
					nilRange := rg.array[rg.top:oldtopi]
					for i := range nilRange {
						nilRange[i] = nil
					}
				}
				//for i := rg.top; i < oldtop; i++ {
				//	rg.array[i] = LNil
				//}
			}
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA + 3 + 2
				vali := reg.Get(RA + 2)
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA + 3 + 1
				vali := reg.Get(RA + 1)
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA + 3
				vali := reg.Get(RA)
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			L.callR(2, nret, RA+3)
			if value := reg.Get(RA + 3); value != LNil {
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
				{
					rg := reg
					regi := RA + 2
					vali := value
					newSize := regi + 1
					// this section is inlined by go-inline
					// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = vali
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
				pc := cf.Fn.Proto.Code[cf.Pc]
				cf.Pc += int(pc&0x3ffff) - opMaxArgSbx
			}
			cf.Pc++
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_SETLIST
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff)    //GETB
			C := int(inst>>9) & 0x1ff //GETC
			if C == 0 {
				C = int(cf.Fn.Proto.Code[cf.Pc])
				cf.Pc++
			}
			offset := (C - 1) * FieldsPerFlush
			table := reg.Get(RA).(*LTable)
			nelem := B
			if B == 0 {
				nelem = reg.Top() - RA - 1
			}
			for i := 1; i <= nelem; i++ {
				L.chargeGas(1)
				table.RawSetInt(offset+i, reg.Get(RA+i))
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_CLOSE
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			closeToBeClosedVars(L, cf, A)
			// this section is inlined by go-inline
			// source function is 'func (ls *LState) closeUpvalues(idx int) ' in '_state.go'
			{
				ls := L
				idx := RA
				if ls.uvcache != nil {
					var prev *Upvalue
					for uv := ls.uvcache; uv != nil; uv = uv.next {
						if uv.index >= idx {
							if prev != nil {
								prev.next = nil
							} else {
								ls.uvcache = nil
							}
							uv.Close()
						}
						prev = uv
					}
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_CLOSURE
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			Bx := int(inst & 0x3ffff) //GETBX
			proto := cf.Fn.Proto.FunctionPrototypes[Bx]
			closure := newLFunctionL(proto, cf.Fn.Env, int(proto.NumUpvalues))
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
			{
				rg := reg
				regi := RA
				vali := closure
				newSize := regi + 1
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				rg.array[regi] = vali
				if regi >= rg.top {
					rg.top = regi + 1
				}
			}
			for i := 0; i < int(proto.NumUpvalues); i++ {
				inst = cf.Fn.Proto.Code[cf.Pc]
				cf.Pc++
				B := opGetArgB(inst)
				switch opGetOpCode(inst) {
				case OP_MOVE:
					closure.Upvalues[i] = L.findUpvalue(lbase + B)
				case OP_GETUPVAL:
					closure.Upvalues[i] = cf.Fn.Upvalues[B]
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_VARARG
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			nparams := int(cf.Fn.Proto.NumParameters)
			nvarargs := cf.NArgs - nparams
			if nvarargs < 0 {
				nvarargs = 0
			}
			nwant := B - 1
			if B == 0 {
				nwant = nvarargs
			}
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) CopyRange(regv, start, limit, n int) ' in '_state.go'
			{
				rg := reg
				regv := RA
				start := cf.Base + nparams + 1
				limit := cf.LocalBase
				n := nwant
				newSize := regv + n
				// this section is inlined by go-inline
				// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
				{
					requiredSize := newSize
					if requiredSize > cap(rg.array) {
						rg.resize(requiredSize)
					}
				}
				if limit == -1 || limit > rg.top {
					limit = rg.top
				}
				L.chargeGas(uint64(n))
				for i := 0; i < n; i++ {
					srcIdx := start + i
					if srcIdx >= limit || srcIdx < 0 {
						rg.array[regv+i] = LNil
					} else {
						rg.array[regv+i] = rg.array[srcIdx]
					}
				}

				// values beyond top don't need to be valid LValues, so setting them to nil is fine
				// setting them to nil rather than LNil lets us invoke the golang memclr opto
				oldtop := rg.top
				rg.top = regv + n
				if rg.top < oldtop {
					nilRange := rg.array[rg.top:oldtop]
					for i := range nilRange {
						nilRange[i] = nil
					}
				}
			}
			return 0
		},
		opArith, // OP_BAND
		opArith, // OP_BOR
		opArith, // OP_BXOR
		opArith, // OP_SHL
		opArith, // OP_SHR
		opArith, // OP_IDIV
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_BNOT
			reg := L.reg
			cf := L.currentFrame
			lbase := cf.LocalBase
			A := int(inst>>18) & 0xff //GETA
			RA := lbase + A
			B := int(inst & 0x1ff) //GETB
			unaryv := L.rkValue(B)
			if lv, ok := unaryv.(LUint256); ok {
				result := lu256Bnot(lv)
				{
					rg := reg
					regi := RA
					newSize := regi + 1
					{
						requiredSize := newSize
						if requiredSize > cap(rg.array) {
							rg.resize(requiredSize)
						}
					}
					rg.array[regi] = result
					if regi >= rg.top {
						rg.top = regi + 1
					}
				}
			} else {
				if str, ok := unaryv.(LString); ok {
					if parsed, err := parseNumber(string(str)); err == nil {
						result := lu256Bnot(parsed)
						{
							rg := reg
							regi := RA
							newSize := regi + 1
							{
								requiredSize := newSize
								if requiredSize > cap(rg.array) {
									rg.resize(requiredSize)
								}
							}
							rg.array[regi] = result
							if regi >= rg.top {
								rg.top = regi + 1
							}
						}
						return 0
					}
				}
				op := L.metaOp1(unaryv, "__bnot")
				if op.Type() == LTFunction {
					reg.Push(op)
					reg.Push(unaryv)
					reg.Push(unaryv)
					L.Call(2, 1)
					{
						rg := reg
						regi := RA
						vali := reg.Pop()
						newSize := regi + 1
						{
							requiredSize := newSize
							if requiredSize > cap(rg.array) {
								rg.resize(requiredSize)
							}
						}
						rg.array[regi] = vali
						if regi >= rg.top {
							rg.top = regi + 1
						}
					}
				} else {
					L.RaiseError("__bnot undefined")
				}
			}
			return 0
		},
		func(L *LState, inst uint32, baseframe *callFrame) int { //OP_NOP
			return 0
		},
	}
}

func closeToBeClosedVars(L *LState, cf *callFrame, minReg int) {
	if cf == nil || cf.Fn == nil || cf.Fn.Proto == nil || len(cf.Fn.Proto.DbgLocals) == 0 {
		return
	}
	pc := cf.Pc - 1

	type closeCandidate struct {
		name string
		reg  int
	}
	candidates := make([]closeCandidate, 0, 4)
	for _, li := range cf.Fn.Proto.DbgLocals {
		if li.Attr != dbgLocalAttrClose {
			continue
		}
		if li.Reg < minReg {
			continue
		}
		idx := cf.LocalBase + li.Reg
		if idx < 0 || idx >= L.reg.Top() {
			continue
		}
		if li.StartPc <= pc && pc <= li.EndPc {
			candidates = append(candidates, closeCandidate{name: li.Name, reg: li.Reg})
		}
	}
	if len(candidates) == 0 {
		return
	}
	// Lua closes variables in reverse declaration order.
	sort.Slice(candidates, func(i, j int) bool {
		return candidates[i].reg > candidates[j].reg
	})
	for _, c := range candidates {
		idx := cf.LocalBase + c.reg
		v := L.reg.Get(idx)
		if v == LNil || v == LFalse {
			continue
		}
		op := L.metaOp1(v, "__close")
		fn, ok := op.(*LFunction)
		if !ok {
			L.RaiseError("variable '%s' has no __close metamethod", c.name)
			return
		}
		L.reg.Push(fn)
		L.reg.Push(v)
		L.reg.Push(LNil) // no error object during normal close
		L.Call(2, 0)
		// Mark as closed to avoid duplicate invocation from later OP_CLOSE.
		L.reg.Set(idx, LNil)
	}
}

func opArith(L *LState, inst uint32, baseframe *callFrame) int { // arithmetic/bitwise binary ops
	reg := L.reg
	cf := L.currentFrame
	lbase := cf.LocalBase
	A := int(inst>>18) & 0xff //GETA
	RA := lbase + A
	opcode := int(inst >> 26) //GETOPCODE
	B := int(inst & 0x1ff)    //GETB
	C := int(inst>>9) & 0x1ff //GETC
	lhs := L.rkValue(B)
	rhs := L.rkValue(C)
	v1, ok1 := lhs.(LUint256)
	v2, ok2 := rhs.(LUint256)
	if ok1 && ok2 {
		v := numberArith(L, opcode, LUint256(v1), LUint256(v2))
		// this section is inlined by go-inline
		// source function is 'func (rg *registry) SetNumber(regi int, vali LUint256) ' in '_state.go'
		{
			rg := reg
			regi := RA
			vali := v
			newSize := regi + 1
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
			{
				requiredSize := newSize
				if requiredSize > cap(rg.array) {
					rg.resize(requiredSize)
				}
			}
			rg.array[regi] = rg.alloc.LUint256ToI(vali)
			if regi >= rg.top {
				rg.top = regi + 1
			}
		}
	} else {
		v := objectArith(L, opcode, lhs, rhs)
		// this section is inlined by go-inline
		// source function is 'func (rg *registry) Set(regi int, vali LValue) ' in '_state.go'
		{
			rg := reg
			regi := RA
			vali := v
			newSize := regi + 1
			// this section is inlined by go-inline
			// source function is 'func (rg *registry) checkSize(requiredSize int) ' in '_state.go'
			{
				requiredSize := newSize
				if requiredSize > cap(rg.array) {
					rg.resize(requiredSize)
				}
			}
			rg.array[regi] = vali
			if regi >= rg.top {
				rg.top = regi + 1
			}
		}
	}
	return 0
}

func luaModulo(lhs, rhs LUint256) LUint256 {
	return lu256Mod(lhs, rhs)
}

func numberArith(L *LState, opcode int, lhs, rhs LUint256) LUint256 {
	switch opcode {
	case OP_ADD:
		return lu256Add(lhs, rhs)
	case OP_SUB:
		return lu256Sub(lhs, rhs)
	case OP_MUL:
		return lu256Mul(lhs, rhs)
	case OP_DIV:
		if lu256IsZero(rhs) {
			L.RaiseError("attempt to perform 'n/0'")
		}
		return lu256Div(lhs, rhs)
	case OP_IDIV:
		if lu256IsZero(rhs) {
			L.RaiseError("attempt to perform 'n//0'")
		}
		return lu256FloorDiv(lhs, rhs)
	case OP_MOD:
		if lu256IsZero(rhs) {
			L.RaiseError("attempt to perform 'n%%0'")
		}
		return lu256Mod(lhs, rhs)
	case OP_POW:
		return lu256Pow(lhs, rhs)
	case OP_BAND:
		return lu256Band(lhs, rhs)
	case OP_BOR:
		return lu256Bor(lhs, rhs)
	case OP_BXOR:
		return lu256Bxor(lhs, rhs)
	case OP_SHL:
		return lu256Shl(lhs, lu256ShiftAmount(rhs))
	case OP_SHR:
		return lu256Shr(lhs, lu256ShiftAmount(rhs))
	default:
		panic("should not reach here")
	}
	return LUint256Zero
}

func objectArith(L *LState, opcode int, lhs, rhs LValue) LValue {
	event := ""
	switch opcode {
	case OP_ADD:
		event = "__add"
	case OP_SUB:
		event = "__sub"
	case OP_MUL:
		event = "__mul"
	case OP_DIV:
		event = "__div"
	case OP_MOD:
		event = "__mod"
	case OP_POW:
		event = "__pow"
	case OP_BAND:
		event = "__band"
	case OP_BOR:
		event = "__bor"
	case OP_BXOR:
		event = "__bxor"
	case OP_SHL:
		event = "__shl"
	case OP_SHR:
		event = "__shr"
	case OP_IDIV:
		event = "__idiv"
	}
	op := L.metaOp2(lhs, rhs, event)
	if _, ok := op.(*LFunction); ok {
		L.reg.Push(op)
		L.reg.Push(lhs)
		L.reg.Push(rhs)
		L.Call(2, 1)
		return L.reg.Pop()
	}
	if str, ok := lhs.(LString); ok {
		if lnum, err := parseNumber(string(str)); err == nil {
			lhs = lnum
		}
	}
	if str, ok := rhs.(LString); ok {
		if rnum, err := parseNumber(string(str)); err == nil {
			rhs = rnum
		}
	}
	if v1, ok1 := lhs.(LUint256); ok1 {
		if v2, ok2 := rhs.(LUint256); ok2 {
			return numberArith(L, opcode, LUint256(v1), LUint256(v2))
		}
	}
	L.RaiseError(fmt.Sprintf("cannot perform %v operation between %v and %v",
		strings.TrimLeft(event, "_"), lhs.Type().String(), rhs.Type().String()))

	return LNil
}

func stringConcat(L *LState, total, last int) LValue {
	rhs := L.reg.Get(last)
	total--
	for i := last - 1; total > 0; {
		lhs := L.reg.Get(i)
		if !(LVCanConvToString(lhs) && LVCanConvToString(rhs)) {
			op := L.metaOp2(lhs, rhs, "__concat")
			if op.Type() == LTFunction {
				L.reg.Push(op)
				L.reg.Push(lhs)
				L.reg.Push(rhs)
				L.Call(2, 1)
				rhs = L.reg.Pop()
				total--
				i--
			} else {
				L.RaiseError("cannot perform concat operation between %v and %v", lhs.Type().String(), rhs.Type().String())
				return LNil
			}
		} else {
			buf := make([]string, total+1)
			rightStr := LVAsString(rhs)
			outLen := int64(len(rightStr))
			buf[total] = rightStr
			for total > 0 {
				L.chargeGas(1)
				lhs = L.reg.Get(i)
				if !LVCanConvToString(lhs) {
					break
				}
				leftStr := LVAsString(lhs)
				addStringResultBytes(L, "concat", &outLen, len(leftStr))
				buf[total-1] = leftStr
				i--
				total--
			}
			rhs = LString(strings.Join(buf, ""))
		}
	}
	return rhs
}

func lessThan(L *LState, lhs, rhs LValue) bool {
	// optimization for numbers
	if v1, ok1 := lhs.(LUint256); ok1 {
		if v2, ok2 := rhs.(LUint256); ok2 {
			return lu256Cmp(v1, v2) < 0
		}
		// Mixed types: try __lt metamethod on either operand before erroring.
		m := L.metaOp1(lhs, "__lt")
		if m.Type() != LTFunction {
			m = L.metaOp1(rhs, "__lt")
		}
		if m.Type() == LTFunction {
			L.reg.Push(m)
			L.reg.Push(lhs)
			L.reg.Push(rhs)
			L.Call(2, 1)
			return LVAsBool(L.reg.Pop())
		}
		L.RaiseError("attempt to compare %v with %v", lhs.Type().String(), rhs.Type().String())
	}
	if lhs.Type() != rhs.Type() {
		// Try __lt metamethod on either operand for mixed-type comparisons.
		m := L.metaOp1(lhs, "__lt")
		if m.Type() != LTFunction {
			m = L.metaOp1(rhs, "__lt")
		}
		if m.Type() == LTFunction {
			L.reg.Push(m)
			L.reg.Push(lhs)
			L.reg.Push(rhs)
			L.Call(2, 1)
			return LVAsBool(L.reg.Pop())
		}
		L.RaiseError("attempt to compare %v with %v", lhs.Type().String(), rhs.Type().String())
		return false
	}
	ret := false
	switch lhs.Type() {
	case LTString:
		ret = strCmp(string(lhs.(LString)), string(rhs.(LString))) < 0
	default:
		ret = objectRationalWithError(L, lhs, rhs, "__lt")
	}
	return ret
}

func equals(L *LState, lhs, rhs LValue, raw bool) bool {
	lt := lhs.Type()
	if lt != rhs.Type() {
		return false
	}

	ret := false
	switch lt {
	case LTNil:
		ret = true
	case LTUint256:
		v1, _ := lhs.(LUint256)
		v2, _ := rhs.(LUint256)
		ret = lu256Cmp(v1, v2) == 0
	case LTBool:
		ret = bool(lhs.(LBool)) == bool(rhs.(LBool))
	case LTString:
		ret = string(lhs.(LString)) == string(rhs.(LString))
	case LTUserData, LTTable:
		if lhs == rhs {
			ret = true
		} else if !raw {
			switch objectRational(L, lhs, rhs, "__eq") {
			case 1:
				ret = true
			default:
				ret = false
			}
		}
	default:
		ret = lhs == rhs
	}
	return ret
}

func objectRationalWithError(L *LState, lhs, rhs LValue, event string) bool {
	switch objectRational(L, lhs, rhs, event) {
	case 1:
		return true
	case 0:
		return false
	}
	L.RaiseError("attempt to compare %v with %v", lhs.Type().String(), rhs.Type().String())
	return false
}

func objectRational(L *LState, lhs, rhs LValue, event string) int {
	m1 := L.metaOp1(lhs, event)
	m2 := L.metaOp1(rhs, event)
	// Lua 5.3+: for __eq, call the metamethod if either operand has it.
	// For __lt/__le, both operands must share the same handler (standard behaviour).
	var m LValue
	if event == "__eq" {
		if m1.Type() == LTFunction {
			m = m1
		} else if m2.Type() == LTFunction {
			m = m2
		}
	} else {
		if m1.Type() == LTFunction && m1 == m2 {
			m = m1
		}
	}
	if m != nil {
		L.reg.Push(m)
		L.reg.Push(lhs)
		L.reg.Push(rhs)
		L.Call(2, 1)
		if LVAsBool(L.reg.Pop()) {
			return 1
		}
		return 0
	}
	return -1
}
